version: '3.8'

services:
  web:
    image: ruby:3.2
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/myapp
    working_dir: /myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
