databases:
  - name: database
    databaseName: depth_and_core
    user: depth_and_core_user

services:
  - type: web
    name: depth_and_core
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: ${RAILS_MASTER_KEY}
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        value: ${SECRET_KEY_BASE}
      # Add any other necessary environment variables here